"""The stack and Eggomi agree on the channel bytes and the signed row bytes.

``vectors/eggomi-interop.json`` was generated by Eggomi's own code
(``interop/eggomi-interop.mjs`` driving ``channel.ts``, ``registry.ts`` and
``packages/noise``). ``InteropVectorTests`` recomputes every output with the
stack's Python and always runs.

``LiveEggomiTests`` runs Eggomi's TypeScript against the stack over real
sockets, and regenerates the vectors file to prove it is still Eggomi's
output. It needs ``node`` and ``CAH_EGGOMI_CHECKOUT`` (see
``scripts/eggomi-interop.sh``) and is skipped, by name, without them.
"""

# SPDX-FileCopyrightText: © 2026 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import json
import os
import shutil
import socket
import subprocess
import tempfile
import threading
import time
import unittest
from pathlib import Path
from typing import Any, Dict, List, Optional

from cah.channel import (
    PROLOGUE,
    ChannelClosed,
    ChannelError,
    client_handshake,
    read_frame,
    server_handshake,
    write_gate_denial,
)
from cah.launcher import LauncherSigner, row_attributed, row_message
from cah.noise import public_from_private
from cah.registry import (
    AdmissionRegistry,
    bind_process,
    rebind_channel,
    save_registry,
)
from cah.rpc import open_channel, rpc_error, rpc_ok, serve

SUITE = Path(__file__).resolve().parents[1]
VECTORS = SUITE / "vectors" / "eggomi-interop.json"
INTEROP = SUITE / "interop"


def _vectors() -> Dict[str, Any]:
    return json.loads(VECTORS.read_text(encoding="utf-8"))


class _Tap:
    """A socket that records every byte this side sends."""

    def __init__(self, sock: socket.socket) -> None:
        self.sock = sock
        self.sent = bytearray()

    def sendall(self, data: bytes) -> None:
        self.sent.extend(data)
        self.sock.sendall(data)

    def recv(self, size: int) -> bytes:
        return self.sock.recv(size)


class InteropVectorTests(unittest.TestCase):
    """Python reproduces every byte Eggomi's code produced."""

    def test_channel_bytes_on_the_wire(self) -> None:
        """Fixed keys and ephemerals give Eggomi's frames, both directions."""
        vectors = _vectors()
        fixed = vectors["fixed"]
        expect = vectors["channel"]
        self.assertEqual(PROLOGUE.decode(), expect["prologue"])
        workload = bytes.fromhex(fixed["workload_static"])
        keeper = bytes.fromhex(fixed["keeper_static"])
        self.assertEqual(public_from_private(workload).hex(), expect["workload_public"])
        self.assertEqual(public_from_private(keeper).hex(), expect["keeper_public"])
        left, right = socket.socketpair()
        self.addCleanup(left.close)
        self.addCleanup(right.close)
        client_tap, server_tap = _Tap(left), _Tap(right)
        holder: Dict[str, Any] = {}

        def server() -> None:
            session = server_handshake(
                server_tap,  # type: ignore[arg-type]
                keeper,
                public_from_private(workload),
                ephemeral=bytes.fromhex(fixed["keeper_ephemeral"]),
            )
            holder["hash"] = session.handshake_hash
            holder["request"] = session.read()
            session.write(json.loads(expect["response_json"]))

        thread = threading.Thread(target=server)
        thread.start()
        session = client_handshake(
            client_tap,  # type: ignore[arg-type]
            workload,
            public_from_private(keeper),
            ephemeral=bytes.fromhex(fixed["workload_ephemeral"]),
        )
        session.write(json.loads(expect["request_json"]))
        response = session.read()
        thread.join(timeout=5)
        self.assertEqual(
            bytes(client_tap.sent).hex(),
            expect["message1_frame"] + expect["request_frame"],
        )
        self.assertEqual(
            bytes(server_tap.sent).hex(),
            expect["message2_frame"] + expect["response_frame"],
        )
        self.assertEqual(session.handshake_hash.hex(), expect["handshake_hash"])
        self.assertEqual(holder["hash"].hex(), expect["handshake_hash"])
        self.assertEqual(holder["request"], json.loads(expect["request_json"]))
        self.assertEqual(response, json.loads(expect["response_json"]))

    def test_refusal_frame(self) -> None:
        """0x00 and the ASCII code, behind a u16 length."""
        expect = _vectors()["channel"]
        left, right = socket.socketpair()
        self.addCleanup(left.close)
        self.addCleanup(right.close)
        tap = _Tap(right)
        write_gate_denial(tap, expect["refusal_code"])  # type: ignore[arg-type]
        self.assertEqual(bytes(tap.sent).hex(), expect["refusal_frame"])

    def test_row_messages_and_signatures(self) -> None:
        """The rowMessage bytes and the Ed25519 signature are identical."""
        vectors = _vectors()
        fixed = vectors["fixed"]
        rows = vectors["rows"]
        signer = LauncherSigner.from_seed(bytes.fromhex(fixed["launcher_seed"]))
        self.assertEqual(signer.public.hex(), rows["launcher_public"])
        for case in rows["cases"]:
            with self.subTest(instance=case["row"]["instance_id"]):
                row = dict(case["row"])
                message = row_message(fixed["trust_domain"], fixed["tenant"], row)
                self.assertEqual(message.hex(), case["message_hex"])
                sig = signer.sign_row(fixed["trust_domain"], fixed["tenant"], row)
                self.assertEqual(sig, case["launcher_sig"])
                row["launcher_sig"] = case["launcher_sig"]
                self.assertTrue(
                    row_attributed(
                        fixed["trust_domain"],
                        fixed["tenant"],
                        row,
                        keys=[signer.public],
                    )
                )
        self.assertEqual(
            rows["eggomi_accepts"],
            [case["row"]["instance_id"] for case in rows["cases"]],
        )
        self.assertEqual(rows["eggomi_refuses"], [])

    def test_saved_registry_carries_eggomis_signatures(self) -> None:
        """save_registry writes the same launcher_sig Eggomi computed."""
        vectors = _vectors()
        fixed = vectors["fixed"]
        signer = LauncherSigner.from_seed(bytes.fromhex(fixed["launcher_seed"]))
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "admission.json"
            rows = [dict(case["row"]) for case in vectors["rows"]["cases"]]
            save_registry(
                path,
                AdmissionRegistry(
                    trust_domain=fixed["trust_domain"],
                    tenant=fixed["tenant"],
                    workloads=rows,
                ),
                signer=signer,
            )
            saved = json.loads(path.read_text(encoding="utf-8"))["workloads"]
        self.assertEqual(
            [row["launcher_sig"] for row in saved],
            [case["launcher_sig"] for case in vectors["rows"]["cases"]],
        )


def _live_skip_reason() -> Optional[str]:
    checkout = os.environ.get("CAH_EGGOMI_CHECKOUT")
    if not checkout:
        return "CAH_EGGOMI_CHECKOUT is not set (scripts/eggomi-interop.sh sets it)"
    if shutil.which("node") is None:
        return "node is not on PATH"
    modules = Path(
        os.environ.get("CAH_EGGOMI_NODE_MODULES") or Path(checkout) / "node_modules"
    )
    for name in ("typescript", "@noble/ciphers", "@noble/curves", "@noble/hashes"):
        if not (modules / name).exists():
            return f"{modules} has no {name}"
    if not (Path(checkout) / "apps/desktop/src/keeper/cah/channel.ts").is_file():
        return f"{checkout} has no apps/desktop/src/keeper/cah/channel.ts"
    return None


_SKIP = _live_skip_reason()


def _node(*args: str) -> List[str]:
    return [
        "node",
        "--import",
        str(INTEROP / "ts-loader.mjs"),
        str(INTEROP / "eggomi-interop.mjs"),
        *args,
    ]


def _wait_ready(root: Path, role: str) -> str:
    ready = root / "ready" / role
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        if ready.is_file() and ready.stat().st_size:
            return ready.read_text(encoding="utf-8").strip().removeprefix("unix:")
        time.sleep(0.02)
    raise AssertionError("keeper did not become ready")


def _row(role: str, instance: str, public: bytes) -> Dict[str, Any]:
    return {
        "role": role,
        "instance_id": instance,
        "boot_id": f"boot-{instance}",
        "boot_generation": 1,
        "boot_history": [f"boot-{instance}"],
        "cert_fingerprint": None,
        "pid": None,
        "starttime": None,
        "channel_public": public.hex(),
    }


@unittest.skipIf(_SKIP is not None, f"live Eggomi interop skipped: {_SKIP}")
class LiveEggomiTests(unittest.TestCase):
    """Eggomi's TypeScript against the stack's Python, on real sockets."""

    def test_vectors_file_is_eggomis_output(self) -> None:
        """Regenerating from Eggomi gives the committed file."""
        done = subprocess.run(
            _node("vectors"), capture_output=True, text=True, check=True, timeout=60
        )
        fresh = json.loads(done.stdout)
        committed = _vectors()
        fresh.pop("eggomi_commit")
        committed.pop("eggomi_commit")
        self.assertEqual(fresh, committed)

    def test_eggomi_reads_a_stack_written_registry(self) -> None:
        """Eggomi's readRegistry accepts signed rows, refuses unsigned or edited."""
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "admission.json"
            save_registry(
                path,
                AdmissionRegistry(
                    trust_domain="lab.cah",
                    tenant="tenant-lab-1",
                    workloads=[
                        _row("omi-runner", "omi-1", b"\x01" * 32),
                        _row("browser-guard", "browser-1", b"\x02" * 32),
                        _row("connector", "connector-1", b"\x03" * 32),
                    ],
                ),
            )
            bind_process(path, "omi-1", os.getpid())
            raw = json.loads(path.read_text(encoding="utf-8"))
            del raw["workloads"][1]["launcher_sig"]
            raw["workloads"][2]["boot_id"] = "boot-other"
            raw["workloads"][2]["boot_history"] = ["boot-other"]
            path.write_text(json.dumps(raw), encoding="utf-8")
            public = LauncherSigner.at(path.parent / "launcher").public.hex()
            done = subprocess.run(
                _node("verify-registry", str(path), public),
                capture_output=True,
                text=True,
                check=True,
                timeout=60,
            )
        reading = json.loads(done.stdout)
        self.assertEqual(reading["rows"], ["omi-1"])
        self.assertEqual(
            reading["refused"],
            [
                {"instance_id": "browser-1", "reason": "unattributed"},
                {"instance_id": "connector-1", "reason": "unattributed"},
            ],
        )

    def test_eggomi_workload_calls_the_stack_keeper(self) -> None:
        """openChannel() through the stack's pidfd gate and KK server."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            workload = os.urandom(32)
            keeper = os.urandom(32)
            registry = root / "admission.json"
            save_registry(
                registry,
                AdmissionRegistry(
                    trust_domain="lab.cah",
                    tenant="tenant-lab-1",
                    workloads=[
                        _row("omi-runner", "omi-1", public_from_private(workload)),
                        _row("keeper-core", "keeper-1", public_from_private(keeper)),
                    ],
                ),
            )
            calls: List[str] = []

            def handler(auth: Any, method: str, body: Dict[str, Any]) -> Dict[str, Any]:
                del auth
                calls.append(method)
                if method == "Refuse":
                    return rpc_error("denied_role")
                if method == "Rebind":
                    rebind_channel(registry, "omi-1", os.urandom(32).hex())
                return rpc_ok({"echo": body})

            stop = root / "stop"
            thread = threading.Thread(
                target=serve,
                args=("unix:" + str(root / "k.sock"), "unix", registry, handler, stop),
                kwargs={"role": "keeper-core", "channel_private": keeper},
                daemon=True,
            )
            thread.start()
            try:
                address = _wait_ready(root, "keeper-core")
                plan = [
                    ["Ping", {"n": 1}],
                    ["Refuse", {}],
                    ["Rebind", {}],
                    ["Ping", {}],
                    ["Ping", {}],
                ]
                go = root / "go"
                proc = subprocess.Popen(
                    _node(
                        "client",
                        address,
                        workload.hex(),
                        public_from_private(keeper).hex(),
                        json.dumps(plan),
                        str(go),
                    ),
                    stdout=subprocess.PIPE,
                    text=True,
                )
                bind_process(registry, "omi-1", proc.pid)
                go.write_text("go\n", encoding="utf-8")
                out, _err = proc.communicate(timeout=60)
                results = json.loads(out)["results"]
                self.assertEqual(
                    results,
                    [
                        {"result": {"echo": {"n": 1}}},
                        {"error": "denied_role"},
                        {"result": {"echo": {}}},
                        {"error": "denied_boot"},
                        {"closed": True},
                    ],
                )
                self.assertEqual(calls, ["Ping", "Refuse", "Rebind"])
                stranger = subprocess.run(
                    _node(
                        "client",
                        address,
                        os.urandom(32).hex(),
                        public_from_private(keeper).hex(),
                        "[]",
                    ),
                    capture_output=True,
                    text=True,
                    timeout=60,
                    check=True,
                )
                self.assertEqual(
                    json.loads(stranger.stdout), {"denial": "denied_unadmitted"}
                )
            finally:
                stop.write_text("stop\n", encoding="utf-8")
                thread.join(timeout=5)

    def test_stack_workload_calls_the_eggomi_keeper(self) -> None:
        """serveChannel() answers the stack client, then refuses on recheck."""
        with tempfile.TemporaryDirectory() as tmp:
            sock_path = str(Path(tmp) / "eggomi.sock")
            workload = os.urandom(32)
            keeper = os.urandom(32)
            proc = subprocess.Popen(
                _node(
                    "server",
                    sock_path,
                    keeper.hex(),
                    public_from_private(workload).hex(),
                    "2",
                ),
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                text=True,
            )
            try:
                assert proc.stdout is not None
                self.assertEqual(proc.stdout.readline().strip(), "ready")
                sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
                sock.settimeout(5)
                sock.connect(sock_path)
                channel = open_channel(sock, workload, public_from_private(keeper))
                self.assertEqual(
                    channel.call("Ping", {"n": 1}),
                    rpc_ok({"method": "Ping", "echo": {"n": 1}}),
                )
                self.assertEqual(channel.call("Refuse", {}), rpc_error("denied_role"))
                self.assertEqual(channel.call("Ping", {}), rpc_error("denied_boot"))
                with self.assertRaises(ChannelClosed):
                    read_frame(sock)
                sock.close()
                other = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
                other.settimeout(5)
                other.connect(sock_path)
                with self.assertRaises(ChannelError):
                    client_handshake(other, os.urandom(32), public_from_private(keeper))
                other.close()
            finally:
                assert proc.stdin is not None and proc.stdout is not None
                proc.stdin.close()
                proc.wait(timeout=10)
                proc.stdout.close()


if __name__ == "__main__":
    unittest.main()
